#! /bin/sh

sxhkd &

bspc monitor -d I II III IV

bspc config automatic_scheme      "longest_side"
bspc config initial_polarity	  "first_child"
bspc config border_width          3
bspc config window_gap            1
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false

bspc config normal_border_color   "#665c54"
bspc config active_border_color   "#a89984"
bspc config focused_border_color  "#a89984"

setxkbmap -option grp:caps_toggle us,ru &
wmname LG3D
